server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.php;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }

        location /config/ {
                deny all;
                return 403;
        }

        # API Routing - Profiles - byname
        location ~ ^/api/profiles/minecraft/byname/(?<name_captured>[^/]+) {
                include fastcgi_params;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root/api/profiles/minecraft/byname/index.php;
                fastcgi_param QUERY_STRING /$name_captured;
        }

        # API Routing - Profiles
        location ~ ^/api/sessionserver/session/minecraft/profile/(?<uuid_captured>[^/]+)/?$ {
                include fastcgi_params;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root/api/sessionserver/session/minecraft/profile/index.php;
                fastcgi_param QUERY_STRING uuid=$uuid_captured&$query_string;
        }

        # API Routing - hasJoined
        location ~ ^/api/sessionserver/session/minecraft/hasJoined/?$ {
                include fastcgi_params;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root/api/sessionserver/session/minecraft/hasJoined/index.php;
                fastcgi_param QUERY_STRING $query_string;
        }

        # API Routing - join
        location ~ ^/api/sessionserver/session/minecraft/join/?$ {
                include fastcgi_params;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root/api/sessionserver/session/minecraft/join/index.php;
                fastcgi_param QUERY_STRING $query_string;
        }
}