server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.php;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }

        location /config/ {
                deny all;
                return 403;
        }

        # API Routing
        location @profile {
                rewrite ^/api/sessionserver/session/minecraft/profile/([^/]+)/?$ /api/sessionserver/session/minecraft/profile/index.php?uuid=$1 last;
        }

        location ~ ^/api/sessionserver/session/minecraft/profile/(?<uuid_captured>[^/]+)/?$ {
                include fastcgi_params;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root/api/sessionserver/session/minecraft/profile/index.php;
                fastcgi_param QUERY_STRING uuid=$uuid_captured&$query_string;
        }
}